name: build_and_tests
on:
  push:
    paths-ignore:
      - 'bin/**'
      - 'images/**'
      - 'share/**'
      - '.github/**'
      - '**.md'
      - '.gitignore'
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...